import Typography from '@mui/material/Typography'

export const About = () => {
  return (
    <>
      <Typography variant='h4'>About</Typography>
      <Typography variant='h6'>Descripcion</Typography>
      <Typography variant="body2" color="initial">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt, excepturi. Cupiditate ipsa doloribus praesentium minus repellat, vero explicabo unde beatae laudantium odio accusamus eos necessitatibus ut libero ab, inventore ratione quod quae? Atque, natus vitae minima illo deleniti accusamus eaque eum distinctio amet molestiae voluptate facere sed neque fugiat minus ducimus aut incidunt consectetur et esse soluta culpa eligendi. Aspernatur repellat possimus id a ad similique laudantium eaque non. Laudantium corrupti optio natus eaque delectus dolore labore quod numquam perspiciatis nobis porro odio dicta nulla id minus quaerat velit, error nihil esse temporibus quo quidem? Expedita suscipit minima quod repellendus deleniti molestias nam facilis libero fugit. Id ea nam voluptates et impedit autem architecto natus totam non dignissimos? Vel voluptas quidem saepe, optio ex consequuntur doloremque nostrum dolorum praesentium, odio quae distinctio assumenda cum perspiciatis incidunt commodi excepturi repudiandae eveniet alias consectetur veniam? Tempore accusantium nostrum repellat voluptatem, blanditiis modi est iure veniam maiores officia exercitationem nemo ipsum molestias placeat maxime sint sapiente omnis non delectus provident quis atque ipsa esse! Maiores dolores consequatur dolor velit! Odio deserunt quod harum adipisci temporibus nesciunt, placeat odit itaque sed repudiandae aspernatur mollitia nam sunt quidem enim fugiat explicabo cumque voluptatum modi. Voluptates inventore libero voluptatum consectetur dicta! Sint ex possimus adipisci dolore consectetur earum animi rerum mollitia architecto, iure in blanditiis nesciunt laudantium odio natus reiciendis non nostrum aliquid dolorem debitis consequatur. Commodi eligendi dolor hic esse magni itaque exercitationem consequatur impedit qui enim dolorem quas vitae a veritatis, minima, iure corrupti recusandae id doloribus! Rem omnis repudiandae, incidunt dicta similique dolorem laboriosam est non iure at, totam dolorum, quidem corrupti reiciendis explicabo quis exercitationem doloremque facilis ipsa cupiditate atque. Voluptatibus, culpa sit mollitia itaque autem quo officiis dolor minima sequi saepe blanditiis nesciunt eos enim a reprehenderit soluta illum. Libero, neque!
      </Typography>
      <Typography variant='h6'>Centro de ayuda</Typography>
      <Typography variant="body2" color="initial">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Similique nostrum amet possimus voluptatum aliquid, beatae quo unde ducimus necessitatibus error reiciendis itaque pariatur enim, asperiores sit magnam officia perferendis cumque tempore. Ut fugit natus dolorum quisquam cupiditate nulla placeat harum ratione suscipit perspiciatis distinctio, inventore minima repellendus necessitatibus provident voluptatibus eos nam asperiores reiciendis magnam dolor ullam laudantium optio. Praesentium dolor, maxime laudantium, laboriosam tempore quisquam eos voluptate recusandae soluta facilis debitis incidunt doloribus fugiat dolores a modi ex fugit obcaecati dicta at quidem porro? Dignissimos, placeat. Laboriosam ad blanditiis soluta aliquam, odit praesentium provident sed error quas necessitatibus possimus. Hic, quos non laudantium officiis reiciendis ad, blanditiis nesciunt earum saepe eius animi illo dolor odit. In quia quibusdam quam, aliquid nisi laboriosam provident similique praesentium ad laborum, ducimus dicta reprehenderit amet qui! At, dignissimos natus? Repellat facere possimus autem sequi iste perferendis repudiandae animi laboriosam dignissimos odit. Odio optio eligendi harum pariatur enim sed vitae aspernatur, nam possimus quasi commodi placeat cupiditate? Incidunt rerum nemo similique cupiditate exercitationem ut, excepturi distinctio voluptate nisi voluptatem ab molestiae id blanditiis minus quas eaque suscipit. Architecto dicta delectus, ipsa fuga debitis facere quia veritatis dolore eum! Quaerat pariatur molestias facilis corrupti tenetur.
      </Typography>
    </>
  )
}
